import { approveAndMerge } from './approve-and-merge.js';
import { parseRalphLoopConfig } from './config.js';
import { createPullRequest } from './create-pr.js';
import { GhClient } from './gh-client.js';
import { defaultRunCommand, emitProgress, runCiChecks, toAttemptRecord } from './ralph-helpers.js';
import { readReviewFeedback } from './read-comments.js';
import { requestReviews } from './request-review.js';
import { respondToFeedback } from './respond-to-review.js';
import { WorktreeManager } from './worktree-manager.js';
import type { RalphLoopConfig, RalphLoopState, Result } from './types.js';

interface RalphLoopDependencies {
  ghClient?: GhClient;
  worktreeManager?: WorktreeManager;
  runCommand?: (command: string, cwd: string) => Result<string, string>;
  now?: () => Date;
}

export function runRalphLoop(
  inputConfig: RalphLoopConfig,
  dependencies: RalphLoopDependencies = {},
): RalphLoopState {
  const config = parseRalphLoopConfig(inputConfig);
  const ghClient = dependencies.ghClient ?? new GhClient();
  const worktreeManager =
    dependencies.worktreeManager ?? new WorktreeManager({ baseBranch: config.baseBranch });
  const runCommand = dependencies.runCommand ?? defaultRunCommand;
  const now = dependencies.now ?? (() => new Date());

  const state: RalphLoopState = {
    attempt: 0,
    prNumber: null,
    status: 'running',
    errors: [],
    history: [],
  };

  const branchName = `${config.branchPrefix}${Date.now()}`;
  const createdWorktree = worktreeManager.create(branchName);
  if (!createdWorktree.ok) {
    state.status = 'failed';
    state.errors.push(createdWorktree.error.message);
    return state;
  }

  emitProgress('worktree_created', {
    branch: branchName,
    path: createdWorktree.value.path,
  });

  try {
    for (let attempt = 1; attempt <= config.maxAttempts; attempt += 1) {
      state.attempt = attempt;
      const startedAt = now().getTime();
      emitProgress('attempt_started', { attempt });

      const contextBlock = [
        `Task: ${config.taskDescription}`,
        `Attempt: ${attempt}`,
        state.errors.length > 0
          ? `Known errors: ${state.errors.join(' | ')}`
          : 'Known errors: none',
      ].join('\n');

      const agentResult = runCommand(
        `${config.agentCommand} "${contextBlock}"`,
        createdWorktree.value.path,
      );
      if (!agentResult.ok) {
        state.errors.push(agentResult.error);
        state.history.push(
          toAttemptRecord(
            attempt,
            'run_agent',
            'failure',
            now().getTime() - startedAt,
            now(),
            agentResult.error,
          ),
        );
        emitProgress('agent_failed', { attempt, error: agentResult.error });
        continue;
      }

      const ciResult = runCiChecks(runCommand, createdWorktree.value.path);
      if (!ciResult.ok) {
        state.errors.push(ciResult.error);
        state.history.push(
          toAttemptRecord(
            attempt,
            'ci_checks',
            'failure',
            now().getTime() - startedAt,
            now(),
            ciResult.error,
          ),
        );
        emitProgress('ci_failed', { attempt, error: ciResult.error });
        continue;
      }

      if (state.prNumber === null) {
        const createPrResult = createPullRequest(
          {
            title: `Ralph Loop: ${config.taskDescription}`,
            summary: ['Automated PR generated by Ralph loop.'],
            changes: ['Applied agent-generated changes in isolated worktree.'],
            testResults: ['typecheck passed', 'lint passed', 'test passed'],
            metadata: {
              attempt: String(attempt),
              branch: branchName,
            },
            branch: branchName,
            baseBranch: config.baseBranch,
          },
          ghClient,
        );
        if (!createPrResult.ok) {
          state.errors.push(createPrResult.error.message);
          state.history.push(
            toAttemptRecord(
              attempt,
              'create_pr',
              'failure',
              now().getTime() - startedAt,
              now(),
              createPrResult.error.message,
            ),
          );
          emitProgress('pr_create_failed', { attempt, error: createPrResult.error.message });
          continue;
        }

        state.prNumber = createPrResult.value.number;
        const reviewRequestResult = requestReviews(
          {
            prNumber: createPrResult.value.number,
            humanReviewers: config.reviewers.filter((reviewer) => !reviewer.startsWith('agent:')),
            agentReviewers: config.reviewers
              .filter((reviewer) => reviewer.startsWith('agent:'))
              .map((reviewer) => reviewer.replace('agent:', '')),
          },
          ghClient,
        );

        if (!reviewRequestResult.ok) {
          state.errors.push(reviewRequestResult.error.message);
          state.history.push(
            toAttemptRecord(
              attempt,
              'request_review',
              'failure',
              now().getTime() - startedAt,
              now(),
              reviewRequestResult.error.message,
            ),
          );
          emitProgress('review_request_failed', {
            attempt,
            error: reviewRequestResult.error.message,
          });
          continue;
        }
      }

      if (state.prNumber === null) {
        state.errors.push('PR number missing after PR creation phase.');
        continue;
      }

      const feedbackResult = readReviewFeedback(state.prNumber, ghClient);
      if (!feedbackResult.ok) {
        state.errors.push(feedbackResult.error.message);
        state.history.push(
          toAttemptRecord(
            attempt,
            'read_review_feedback',
            'failure',
            now().getTime() - startedAt,
            now(),
            feedbackResult.error.message,
          ),
        );
        continue;
      }

      if (feedbackResult.value.actionable.length > 0) {
        const respondResult = respondToFeedback(
          {
            prNumber: state.prNumber,
            comments: feedbackResult.value.actionable,
          },
          ghClient,
        );
        if (!respondResult.ok) {
          state.errors.push(respondResult.error.message);
        }

        state.history.push(
          toAttemptRecord(
            attempt,
            'handle_review_feedback',
            'failure',
            now().getTime() - startedAt,
            now(),
            `Actionable comments remaining: ${feedbackResult.value.actionable.length}`,
          ),
        );
        emitProgress('review_feedback_received', {
          attempt,
          actionableComments: feedbackResult.value.actionable.length,
        });
        continue;
      }

      if (config.autoMerge) {
        const mergeResult = approveAndMerge(
          {
            prNumber: state.prNumber,
            gates: config.qualityGates,
            cwd: createdWorktree.value.path,
          },
          ghClient,
        );
        if (!mergeResult.ok) {
          state.errors.push(mergeResult.error.message);
          state.history.push(
            toAttemptRecord(
              attempt,
              'approve_and_merge',
              'failure',
              now().getTime() - startedAt,
              now(),
              mergeResult.error.message,
            ),
          );
          continue;
        }
      }

      state.history.push(
        toAttemptRecord(attempt, 'complete_attempt', 'success', now().getTime() - startedAt, now()),
      );
      state.status = 'success';
      emitProgress('loop_success', { attempt, prNumber: state.prNumber });
      return state;
    }

    state.status = 'max_attempts_reached';
    if (state.prNumber === null) {
      const failedPrResult = createPullRequest(
        {
          title: `Ralph Loop Failed: ${config.taskDescription}`,
          summary: ['Ralph loop reached max attempts without success.'],
          changes: ['No merge-ready revision produced.'],
          testResults: ['One or more quality checks failed repeatedly.'],
          metadata: {
            attempts: String(config.maxAttempts),
            errors: state.errors.slice(-5).join(' || '),
          },
          branch: branchName,
          baseBranch: config.baseBranch,
          draft: true,
        },
        ghClient,
      );
      if (failedPrResult.ok) {
        state.prNumber = failedPrResult.value.number;
      }
    }
    emitProgress('loop_failed', { attempts: state.attempt, prNumber: state.prNumber });
    return state;
  } finally {
    const cleanupResult = worktreeManager.remove(createdWorktree.value.name);
    if (!cleanupResult.ok) {
      state.errors.push(cleanupResult.error.message);
    }
  }
}
