import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import process from 'node:process';

type PlanStatus = 'active' | 'completed';

type PlanEntry = {
  title: string;
  domain: string;
  created: string;
  fileName: string;
  status: PlanStatus;
};

type Args = {
  plan: string;
};

const ROOT = process.cwd();
const DOCS_DIR = path.join(ROOT, 'docs');
const EXEC_PLANS_DIR = path.join(DOCS_DIR, 'exec-plans');
const ACTIVE_DIR = path.join(EXEC_PLANS_DIR, 'active');
const COMPLETED_DIR = path.join(EXEC_PLANS_DIR, 'completed');
const INDEX_PATH = path.join(DOCS_DIR, 'PLANS.md');

function getArgValue(args: string[], name: string): string | undefined {
  const index = args.indexOf(`--${name}`);
  return index >= 0 ? args[index + 1] : undefined;
}

function parseArgs(argv: string[]): Args {
  const plan = getArgValue(argv, 'plan');
  if (!plan) {
    process.stderr.write('Usage: npx tsx scripts/exec-plan-complete.ts --plan <slug>\n');
    process.exit(1);
  }

  return { plan };
}

function firstMatch(content: string, expression: RegExp): string {
  const match = content.match(expression);
  return match?.[1]?.trim() ?? 'unknown';
}

function parsePlan(filePath: string, status: PlanStatus): PlanEntry {
  const content = readFileSync(filePath, 'utf8');
  const fileName = path.basename(filePath);

  return {
    title: firstMatch(content, /^#\s+(.+)$/m),
    domain: firstMatch(content, /^\*\*Domain:\*\*\s+(.+)$/m),
    created: firstMatch(content, /^\*\*Created:\*\*\s+(.+)$/m),
    fileName,
    status,
  };
}

function readPlans(directoryPath: string, status: PlanStatus): PlanEntry[] {
  if (!existsSync(directoryPath)) {
    return [];
  }

  return readdirSync(directoryPath)
    .filter((name) => name.endsWith('.md') && name !== '.gitkeep')
    .map((name) => path.join(directoryPath, name))
    .filter((filePath) => statSync(filePath).isFile())
    .map((filePath) => parsePlan(filePath, status))
    .sort((left, right) => left.title.localeCompare(right.title));
}

function section(title: string, plans: PlanEntry[], status: PlanStatus): string[] {
  const lines: string[] = [`## ${title}`, ''];

  if (plans.length === 0) {
    lines.push(
      `No ${status} plans are currently indexed.`,
      `Place ${status} plan documents under \`docs/exec-plans/${status}/\`.`,
      '',
    );
    return lines;
  }

  for (const plan of plans) {
    lines.push(
      `- [${plan.title}](exec-plans/${status}/${plan.fileName}) — Domain: ${plan.domain}, Created: ${plan.created}`,
    );
  }

  lines.push('');
  return lines;
}

function regeneratePlanIndex(): void {
  const activePlans = readPlans(ACTIVE_DIR, 'active');
  const completedPlans = readPlans(COMPLETED_DIR, 'completed');

  const lines: string[] = [
    '# Execution Plans Index',
    '',
    'This file is designed to be regenerated by `npx tsx scripts/exec-plan-index.ts`.',
    'It provides a single view of active and completed execution plans.',
    '',
    ...section('Active Plans', activePlans, 'active'),
    ...section('Completed Plans', completedPlans, 'completed'),
  ];

  writeFileSync(INDEX_PATH, `${lines.join('\n')}\n`, 'utf8');
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const sourcePath = path.join(ACTIVE_DIR, `${args.plan}.md`);
  const targetPath = path.join(COMPLETED_DIR, `${args.plan}.md`);

  if (!existsSync(sourcePath)) {
    process.stderr.write(`Plan not found: docs/exec-plans/active/${args.plan}.md\n`);
    process.exit(1);
  }

  if (existsSync(targetPath)) {
    process.stderr.write(`Target already exists: docs/exec-plans/completed/${args.plan}.md\n`);
    process.exit(1);
  }

  mkdirSync(COMPLETED_DIR, { recursive: true });

  const content = readFileSync(sourcePath, 'utf8');
  const updatedContent = content.replace(/^\*\*Status:\*\*\s+active$/m, '**Status:** completed');
  writeFileSync(sourcePath, updatedContent, 'utf8');

  renameSync(sourcePath, targetPath);
  regeneratePlanIndex();

  process.stdout.write(`Completed: docs/exec-plans/completed/${args.plan}.md\n`);
}

main();
