import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

type PlanStatus = 'active' | 'completed';

type PlanEntry = {
  title: string;
  domain: string;
  created: string;
  fileName: string;
  status: PlanStatus;
};

type Args = {
  title: string;
  domain: string;
  author: string;
};

const ROOT = process.cwd();
const DOCS_DIR = path.join(ROOT, 'docs');
const EXEC_PLANS_DIR = path.join(DOCS_DIR, 'exec-plans');
const TEMPLATE_PATH = path.join(EXEC_PLANS_DIR, 'TEMPLATE.md');
const ACTIVE_DIR = path.join(EXEC_PLANS_DIR, 'active');
const COMPLETED_DIR = path.join(EXEC_PLANS_DIR, 'completed');
const INDEX_PATH = path.join(DOCS_DIR, 'PLANS.md');

function getArgValue(args: string[], name: string): string | undefined {
  const index = args.indexOf(`--${name}`);
  return index >= 0 ? args[index + 1] : undefined;
}

function parseArgs(argv: string[]): Args {
  const title = getArgValue(argv, 'title');
  const domain = getArgValue(argv, 'domain');
  const author = getArgValue(argv, 'author');

  if (!title || !domain || !author) {
    process.stderr.write(
      'Usage: npx tsx scripts/exec-plan-create.ts --title "Plan Title" --domain "tasks" --author "agent"\n',
    );
    process.exit(1);
  }

  return { title, domain, author };
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function firstMatch(content: string, expression: RegExp): string {
  const match = content.match(expression);
  return match?.[1]?.trim() ?? 'unknown';
}

function parsePlan(filePath: string, status: PlanStatus): PlanEntry {
  const content = readFileSync(filePath, 'utf8');
  const fileName = path.basename(filePath);

  return {
    title: firstMatch(content, /^#\s+(.+)$/m),
    domain: firstMatch(content, /^\*\*Domain:\*\*\s+(.+)$/m),
    created: firstMatch(content, /^\*\*Created:\*\*\s+(.+)$/m),
    fileName,
    status,
  };
}

function readPlans(directoryPath: string, status: PlanStatus): PlanEntry[] {
  if (!existsSync(directoryPath)) {
    return [];
  }

  return readdirSync(directoryPath)
    .filter((name) => name.endsWith('.md') && name !== '.gitkeep')
    .map((name) => path.join(directoryPath, name))
    .filter((filePath) => statSync(filePath).isFile())
    .map((filePath) => parsePlan(filePath, status))
    .sort((left, right) => left.title.localeCompare(right.title));
}

function section(title: string, plans: PlanEntry[], status: PlanStatus): string[] {
  const lines: string[] = [`## ${title}`, ''];

  if (plans.length === 0) {
    lines.push(
      `No ${status} plans are currently indexed.`,
      `Place ${status} plan documents under \`docs/exec-plans/${status}/\`.`,
      '',
    );
    return lines;
  }

  for (const plan of plans) {
    lines.push(
      `- [${plan.title}](exec-plans/${status}/${plan.fileName}) — Domain: ${plan.domain}, Created: ${plan.created}`,
    );
  }

  lines.push('');
  return lines;
}

function regeneratePlanIndex(): void {
  const activePlans = readPlans(ACTIVE_DIR, 'active');
  const completedPlans = readPlans(COMPLETED_DIR, 'completed');

  const lines: string[] = [
    '# Execution Plans Index',
    '',
    'This file is designed to be regenerated by `npx tsx scripts/exec-plan-index.ts`.',
    'It provides a single view of active and completed execution plans.',
    '',
    ...section('Active Plans', activePlans, 'active'),
    ...section('Completed Plans', completedPlans, 'completed'),
  ];

  writeFileSync(INDEX_PATH, `${lines.join('\n')}\n`, 'utf8');
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const slug = slugify(args.title);

  if (!slug) {
    process.stderr.write('Failed to create a valid slug from title.\n');
    process.exit(1);
  }

  if (!existsSync(TEMPLATE_PATH)) {
    process.stderr.write('Template not found: docs/exec-plans/TEMPLATE.md\n');
    process.exit(1);
  }

  mkdirSync(ACTIVE_DIR, { recursive: true });
  mkdirSync(COMPLETED_DIR, { recursive: true });

  const targetPath = path.join(ACTIVE_DIR, `${slug}.md`);
  if (existsSync(targetPath)) {
    process.stderr.write(`Plan already exists: docs/exec-plans/active/${slug}.md\n`);
    process.exit(1);
  }

  const date = new Date().toISOString().slice(0, 10);
  const template = readFileSync(TEMPLATE_PATH, 'utf8');
  const content = template
    .replace(/\{\{TITLE\}\}/g, args.title)
    .replace(/\{\{DATE\}\}/g, date)
    .replace(/\{\{AUTHOR\}\}/g, args.author)
    .replace(/\{\{DOMAIN\}\}/g, args.domain);

  writeFileSync(targetPath, content, 'utf8');
  regeneratePlanIndex();
  process.stdout.write(`Created: docs/exec-plans/active/${slug}.md\n`);
}

main();
