import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

type PlanStatus = 'active' | 'completed';

type PlanEntry = {
  title: string;
  domain: string;
  created: string;
  fileName: string;
  status: PlanStatus;
};

const ROOT = process.cwd();
const DOCS_DIR = path.join(ROOT, 'docs');
const EXEC_PLANS_DIR = path.join(DOCS_DIR, 'exec-plans');
const ACTIVE_DIR = path.join(EXEC_PLANS_DIR, 'active');
const COMPLETED_DIR = path.join(EXEC_PLANS_DIR, 'completed');
const INDEX_PATH = path.join(DOCS_DIR, 'PLANS.md');

function ensureDirectory(directoryPath: string): void {
  if (!existsSync(directoryPath)) {
    mkdirSync(directoryPath, { recursive: true });
  }
}

function firstMatch(content: string, expression: RegExp): string {
  const match = content.match(expression);
  return match?.[1]?.trim() ?? 'unknown';
}

function parsePlan(filePath: string, status: PlanStatus): PlanEntry {
  const content = readFileSync(filePath, 'utf8');
  const fileName = path.basename(filePath);

  return {
    title: firstMatch(content, /^#\s+(.+)$/m),
    domain: firstMatch(content, /^\*\*Domain:\*\*\s+(.+)$/m),
    created: firstMatch(content, /^\*\*Created:\*\*\s+(.+)$/m),
    fileName,
    status,
  };
}

function readPlans(directoryPath: string, status: PlanStatus): PlanEntry[] {
  if (!existsSync(directoryPath)) {
    return [];
  }

  return readdirSync(directoryPath)
    .filter((name) => name.endsWith('.md') && name !== '.gitkeep')
    .map((name) => path.join(directoryPath, name))
    .filter((filePath) => statSync(filePath).isFile())
    .map((filePath) => parsePlan(filePath, status))
    .sort((left, right) => left.title.localeCompare(right.title));
}

function section(title: string, plans: PlanEntry[], status: PlanStatus): string[] {
  const lines: string[] = [`## ${title}`, ''];

  if (plans.length === 0) {
    lines.push(
      `No ${status} plans are currently indexed.`,
      `Place ${status} plan documents under \`docs/exec-plans/${status}/\`.`,
      '',
    );
    return lines;
  }

  for (const plan of plans) {
    lines.push(
      `- [${plan.title}](exec-plans/${status}/${plan.fileName}) — Domain: ${plan.domain}, Created: ${plan.created}`,
    );
  }

  lines.push('');
  return lines;
}

function buildIndex(activePlans: PlanEntry[], completedPlans: PlanEntry[]): string {
  const lines: string[] = [
    '# Execution Plans Index',
    '',
    'This file is designed to be regenerated by `npx tsx scripts/exec-plan-index.ts`.',
    'It provides a single view of active and completed execution plans.',
    '',
    ...section('Active Plans', activePlans, 'active'),
    ...section('Completed Plans', completedPlans, 'completed'),
  ];

  return `${lines.join('\n')}`;
}

function main(): void {
  ensureDirectory(ACTIVE_DIR);
  ensureDirectory(COMPLETED_DIR);

  const activePlans = readPlans(ACTIVE_DIR, 'active');
  const completedPlans = readPlans(COMPLETED_DIR, 'completed');
  const indexContent = buildIndex(activePlans, completedPlans);

  writeFileSync(INDEX_PATH, `${indexContent}\n`, 'utf8');
  process.stdout.write('Updated: docs/PLANS.md\n');
}

main();
